import { describe, expect, it } from "vitest";
import { drawTicket, hexToBytes, sha256Hex, verifyGame } from "../src/lib/jackpot/fairness";

// Published deterministic test vectors for protocol v1.
// Generated by the production Postgres implementation (jackpot_draw_ticket).
// Any mismatch with the TypeScript verifier blocks deployment.
export const VECTORS = [
  { seed: "00".repeat(32), hash: "66687aadf862bd776c8fc18b8e9f8e20089714856ee233b3902a591d0d5f2925", game: 1, dv: 1, n: 100n, ticket: 6n, counter: 0 },
  { seed: "ff".repeat(32), hash: "af9613760f72635fbdb44a5a0a63c39f12af30f950a6ee5c971be188e89c4051", game: 42, dv: 1, n: 12485n, ticket: 2058n, counter: 0 },
  { seed: "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f", hash: "630dcd2966c4336691125448bbb25b4ff412a49c732db2c8abc1b8581bd710dd", game: 18492, dv: 1, n: 1248500n, ticket: 102468n, counter: 0 },
  { seed: "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08", hash: "954d5a49fd70d9b8bcdb35d252267829957f7ef7fa6c74f88419bdc5e82209f4", game: 7, dv: 1, n: 3n, ticket: 1n, counter: 0 },
  { seed: "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08", hash: "954d5a49fd70d9b8bcdb35d252267829957f7ef7fa6c74f88419bdc5e82209f4", game: 7, dv: 1, n: 9223372036854775807n, ticket: 9043839453122091957n, counter: 0 },
  { seed: "deadbeef".repeat(8), hash: "8200cf0ce11447bf6353cbac964d07d1c390d61d07e6c5d0214450b3add6449b", game: 123456, dv: 1, n: 1n, ticket: 0n, counter: 0 },
];

describe("fairness protocol v1 test vectors", () => {
  for (const v of VECTORS) {
    it(`game ${v.game}, N=${v.n}`, async () => {
      expect(await sha256Hex(hexToBytes(v.seed))).toBe(v.hash);
      const r = await drawTicket(v.seed, v.game, v.dv, v.n);
      expect(r.ticket).toBe(v.ticket);
      expect(r.counter).toBe(v.counter);
    });
  }

  it("ticket is always inside [0, N)", async () => {
    for (let i = 0; i < 200; i++) {
      const seed = Array.from(crypto.getRandomValues(new Uint8Array(32)), (b) => b.toString(16).padStart(2, "0")).join("");
      const n = BigInt(1 + Math.floor(Math.random() * 1e9));
      const { ticket } = await drawTicket(seed, i, 1, n);
      expect(ticket >= 0n && ticket < n).toBe(true);
    }
  });

  it("rejection sampling triggers for ranges that don't divide 2^64", async () => {
    // N = 2^62 + 1 rejects ~25% of raw values, so some rounds must retry
    const n = (1n << 62n) + 1n;
    let retried = 0;
    for (let i = 0; i < 64; i++) {
      const r = await drawTicket("ab".repeat(32), i, 1, n);
      if (r.counter > 0) retried++;
      expect(r.ticket < n).toBe(true);
    }
    expect(retried).toBeGreaterThan(0);
  });

  it("distribution is roughly uniform (chi-square, 3 buckets)", async () => {
    const counts = [0, 0, 0];
    const seed = "11".repeat(32);
    const trials = 3000;
    for (let i = 0; i < trials; i++) counts[Number((await drawTicket(seed, i, 1, 3n)).ticket)]++;
    const exp = trials / 3;
    const chi = counts.reduce((s, c) => s + (c - exp) ** 2 / exp, 0);
    expect(chi).toBeLessThan(13.8); // p ~ 0.001 for df=2
  });

  it("verifyGame accepts a correct record and rejects a tampered one", async () => {
    const v = VECTORS[0];
    const entries = [
      { user_id: "a", ticket_start: 0, ticket_end: 25 },
      { user_id: "b", ticket_start: 25, ticket_end: 75 },
      { user_id: "c", ticket_start: 75, ticket_end: 100 },
    ];
    const game = { id: 1, draw_version: 1, pot_amount: 100, server_seed_hash: v.hash, server_seed: v.seed, winning_ticket: 6, winner_id: "a" };
    expect((await verifyGame(game, entries)).ok).toBe(true);
    expect((await verifyGame({ ...game, winner_id: "b" }, entries)).ok).toBe(false);
    expect((await verifyGame({ ...game, server_seed_hash: "00" }, entries)).ok).toBe(false);
    expect((await verifyGame(game, entries.slice(0, 2))).ok).toBe(false);
  });
});
