// Run: bun scripts/check-guides.ts
import { GUIDES, getGuide, publishedTopics, wordCount } from "../src/content/guides";
import { NEW_GUIDES } from "./new-guides-plan";

const STATIC = new Set([
  "/",
  "/coinflip",
  "/roulette",
  "/fairness",
  "/about",
  "/how-it-works",
  "/terms",
  "/privacy",
  "/responsible-gambling",
  "/wallet",
  "/profile",
  "/guides",
  "/auth",
  "/prestige",
]);
const PLANNED = new Set([
  "what-is-a-crypto-casino",
  "provably-fair-casino",
  "pvp-gambling",
  "pvp-casino-games",
  "peer-to-peer-gambling",
  "head-to-head-betting",
  "coin-flip-for-money",
  "online-coin-flip-game",
  "skill-based-gambling",
  "bet-with-friends-online",
  "rock-paper-scissors-for-money",
  "duel-arena-gambling",
  "osrs-gambling",
  "stake-alternatives",
  "roobet-alternatives",
  "crypto-casino-vs-traditional-casino",
  "crypto-casino-reddit-advice",
  "crypto-casino-usa",
  "crypto-casino-uk",
  "crypto-casino-canada",
  "crypto-casino-australia",
  "crypto-betting-app",
  "gambling-loss-deduction",
  "report-gambling-winnings",
  "gambling-winnings-tax-canada",
  "gambling-tax-australia",
  "is-crypto-gambling-legal",
  "esports-betting-legal",
  "cs2-case-battle",
  "sell-skins-for-crypto",
  "skin-cashout-guide",
  "cs2-trading-sites",
  "fortnite-gambling",
  "roblox-gambling",
  "loot-boxes-and-gambling",
  "steam-wallet-to-cash",
  "bridge-to-base",
  "base-network-fees",
  "coinbase-wallet-to-base",
  "stuck-crypto-transaction",
  "revoke-token-approvals",
  "wallet-security-checklist",
  "best-crypto-wallet-for-gambling",
  "crypto-casino-payment-methods",
  "nonce-and-cursor-provably-fair",
  "seed-rotation-provably-fair",
  "chainlink-vrf-gambling",
  "smart-contract-casino",
  "decentralized-casino-explained",
  "verify-a-casino-bet",
  "sha256-explained",
  "casino-fairness-audits",
  "responsible-gambling-tools",
  "gambling-blocker-apps",
  "gambling-cooling-off-period",
  "underage-gambling-risks",
  "crypto-jackpot",
  "usdc-casino",
  "gambling-budget",
  "csgo-coinflip",
  "cs2-roulette",
  "hmac-sha256-provably-fair",
  "provably-fair-calculator",
  "csgo-jackpot",
  "metamask-casino",
  "is-metamask-safe",
  "how-to-buy-usdc",
  "add-base-network-metamask",
  "crypto-wallet-for-gambling",
  "server-seed-client-seed",
  "provably-fair-roulette",
  "coin-flip-odds",
  "crypto-casino-withdrawals",
  "csgo-gambling-history",
  "commit-reveal-scheme",
  "web3-casino",
  "usdc-vs-usdt-gambling",
  "house-edge",
  "are-online-casinos-rigged",
  "casino-terminology",
  "roulette-colors",
  "crypto-roulette",
  "rng-vs-provably-fair",
  "skin-gambling-vs-crypto",
  "martingale-strategy",
  "gamblers-fallacy",
  "csgo-case-opening",
  "how-to-stop-gambling",
  "crash-gambling",
  "crash-game-strategy",
  "plinko-strategy",
  "mines-game-strategy",
  "hi-lo-strategy",
  "tower-game-strategy",
  "best-casino-game-odds",
  "how-to-calculate-house-edge",
  "keno-strategy",
  "wheel-of-fortune-odds",
  "double-or-nothing-strategy",
  "crash-vs-plinko",
  "cs2-betting",
  "how-to-win-at-roulette",
  "seed-phrase",
  "base-network",
  "gambling-self-exclusion",
  "best-crypto-gambling-sites",
  "best-csgo-gambling-sites",
  "csgo-coinflip-sites",
  "csgo-case-battle-sites",
  "provably-fair-games",
  "bitcoin-casino",
  "solana-casino",
  "litecoin-casino",
  "dogecoin-casino",
  "ethereum-gambling",
  "usdt-casino",
  "stablecoin-payments-gambling",
  "base-vs-ethereum",
  "gas-fees-explained",
  "crypto-bridge",
  "phantom-wallet-gambling",
  "coinbase-wallet-casino",
  "walletconnect-casino",
  "trust-wallet-casino",
  "coinbase-to-metamask-transfer",
  "buy-crypto-with-card",
  "how-to-swap-tokens",
  "instant-withdrawal-casino",
  "no-kyc-casino",
  "anonymous-casino",
  "plinko-gambling",
  "crypto-slots",
  "crypto-dice-game",
  "mines-game-casino",
  "limbo-game-strategy",
  "crypto-blackjack",
  "blackjack-basic-strategy",
  "card-counting",
  "roulette-odds-chart",
  "dice-roll-probability",
  "slot-machine-odds",
  "progressive-jackpot-odds",
  "rtp-explained",
  "how-random-number-generators-work",
  "kelly-criterion",
  "odds-converter",
  "implied-probability",
  "expected-value-gambling",
  "variance-in-gambling",
  "paroli-system",
  "dalembert-strategy",
  "fibonacci-betting-system",
  "esports-betting",
  "rust-gambling",
  "cs2-skin-prices",
  "play-to-earn-games",
  "gamefi",
  "discord-gambling-bot",
  "crypto-gambling-taxes",
  "fake-casino-sites",
  "what-is-a-stablecoin",
  "what-is-usdc",
  "crypto-poker",
  "sports-betting-with-crypto",
  "cold-wallet-vs-hot-wallet",
  "self-custody-wallet",
  "tron-casino",
  "curacao-gambling-license",
  "bitcoin-lottery",
  "proof-of-reserves",
  "cs2-trade-up-calculator",
  "cs2-knife-prices",
  "crypto-horse-racing-betting",
  "avalanche-casino",
  "sweepstakes-casino",
  "social-casino",
  "sweeps-coins-explained",
  "no-deposit-bonus-casino",
  "best-sweepstakes-casinos",
  "gold-coins-vs-sweeps-coins",
  "sweepstakes-casino-legal-states",
  "how-do-sweepstakes-casinos-work",
  "sweepstakes-vs-crypto-casino",
  "casino-wagering-requirements",
  "how-to-play-poker",
  "texas-holdem-rules",
  "poker-hand-rankings",
  "how-to-win-at-poker",
  "poker-for-beginners",
  "poker-tips",
  "texas-holdem-strategy",
  "poker-pot-odds",
  "gto-poker-strategy",
  "video-poker-paytables",
  "three-card-poker-strategy",
  "poker-bankroll-management",
  "esports-betting-sites",
  "lol-betting",
  "valorant-betting",
  "esports-odds-explained",
  "esports-sportsbook",
  "csgo-betting-odds",
  "dota2-betting",
  "how-to-bet-on-esports",
  "rocket-league-betting",
  "live-esports-betting",
  "esports-match-fixing",
  "online-casino-games",
  "live-dealer-casino",
  "baccarat-rules",
  "craps-odds",
  "keno-odds",
  "hi-lo-card-game",
  "casino-hold-em",
  "wheel-of-fortune-casino-game",
  "dice-duel-game",
  "tower-game-casino",
  "pachinko-odds",
  "double-or-nothing-game",
  "where-to-buy-cs2-skins",
  "how-to-sell-cs2-skins",
  "free-cs2-skins",
  "csfloat-vs-skinport",
  "cs2-souvenir-skins",
  "cheapest-covert-skins-cs2",
  "cs2-weekly-drops",
  "cs2-skin-investing",
  "skin-changer-ban-risk",
  "crypto-casino-deposit-fees",
  "lightning-network-gambling",
  "crypto-casino-bonus-codes",
  "polygon-casino",
  "how-crypto-casinos-make-money",
  "what-is-sports-betting",
  "how-to-bet-on-sports",
  "how-does-sports-betting-work",
  "how-old-to-sports-bet",
  "how-to-win-at-sports-betting",
  "sports-betting-legal-states",
  "point-spread-explained",
  "moneyline-betting-explained",
  "parlay-betting-explained",
  "over-under-betting",
  "how-to-play-blackjack",
  "blackjack-rules",
  "blackjack-strategy-chart",
  "blackjack-simulator",
  "blackjack-insurance",
  "when-to-double-down-blackjack",
  "when-to-split-blackjack",
  "how-many-decks-blackjack",
  "free-slots",
  "online-slots-real-money",
  "how-to-play-slots",
  "how-to-win-at-slots",
  "how-do-slot-machines-work",
  "slot-volatility",
  "slot-paylines-explained",
  "bonus-buy-slots",
  "gambling-addiction",
  "gambling-hotline",
  "gambling-addiction-signs",
  "what-is-gambling-addiction",
  "gambling-addiction-treatment",
  "why-is-gambling-addictive",
  "help-someone-gambling-addiction",
  "online-casino-real-money",
  "free-casino-games",
  "casino-bonuses-explained",
  "cashback-casino-bonus",
  "vip-casino-programs",
  "rakeback-explained",
  "casino-tournaments",
  "gambling-age-us",
  "online-gambling",
  "crypto-betting-sites",
  "free-spins-no-deposit",
  "crypto-bingo",
  "tf2-gambling",
  "nft-gambling",
  "crypto-scratch-cards",
  "steam-market-fees",
  "telegram-casino-bot",
  "csgo-trade-up-contract",
  "crypto-casino-license",
  "cs2-inventory-value",
  "cs2-case-odds",
  "martingale-calculator",
  "cs2-float-checker",
  "crypto-lottery",
  "steam-trade-hold",
  "steam-trade-ban",
  "plinko-odds",
  "rtp-calculator",
  "bankroll-calculator",
  "gambling-odds-calculator",
  "crash-cashout-calculator",
  "wagering-requirement-calculator",
  "rust-skin-prices",
  "arbitrum-casino",
  "stablecoin-casino",
  "kick-gambling-streamers",
  "twitch-slots-ban",
  "cs2-agents",
  "most-expensive-cs2-skins",
  "cs2-charms",
  "ledger-vs-trezor",
  "cs2-sticker-crafts",
  "cs2-armory-pass",
  "case-hardened-blue-gem",
  "usdc-apy",
  "cs2-operation",
  "cs2-doppler-phases",
  "aviator-game-guide",
  "are-online-casinos-safe",
  "best-payout-online-casinos",
  "crypto-casino-games",
  "crypto-casino-minimum-deposit",
  "how-do-online-casinos-make-money",
  "how-to-start-an-online-casino",
  "new-crypto-casinos",
  "vpn-casino",
  "online-craps",
  "is-online-casino-legal",
  "online-casino-legal-florida",
  "online-casino-legal-maryland",
  "online-casino-legal-ohio",
  "connect-ledger-to-metamask",
  "does-metamask-report-to-irs",
  "does-metamask-support-bitcoin",
  "does-metamask-support-solana",
  "does-metamask-support-xrp",
  "export-metamask-private-key",
  "how-to-add-litecoin-to-metamask",
  "how-to-delete-metamask-account",
  "how-to-install-metamask",
  "how-to-use-metamask",
  "how-to-withdraw-from-metamask",
  "metamask-login-help",
  "metamask-scams",
  "metamask-swap-fees",
  "what-is-metamask",
  "blockchain-confirmations",
  "sent-crypto-to-wrong-network",
  "crypto-prediction-markets",
  "polymarket-alternatives",
  "live-betting-strategy",
  "prediction-market-legal-us",
  "how-do-sweepstakes-casinos-make-money",
  "new-sweepstakes-casinos",
  "no-deposit-sweepstakes-casinos",
  "aml-gambling",
  "anjouan-gaming-license",
  "casino-withdrawal-pending",
  "ecogra-certification",
  "kahnawake-gaming-license",
  "smart-contract-audit",
  "erc20-vs-trc20",
  "how-to-create-a-crypto-wallet",
  "how-to-send-crypto",
  "what-is-a-crypto-wallet-address",
  "what-is-a-hardware-wallet",
  "stake-casino-review",
  "bc-game-review",
  "roobet-review",
  "gamdom-review",
  "duelbits-review",
  "rollbit-review",
  "cardano-casino",
  "xrp-casino",
  "shiba-inu-casino",
  "monero-casino",
  "binance-coin-casino",
  "ton-casino",
  "crypto-casino-new-zealand",
  "crypto-casino-ireland",
  "crypto-casino-netherlands",
  "crypto-casino-south-africa",
  "crypto-casino-india",
  "stake-vs-roobet",
  "gamdom-alternatives",
  "duelbits-alternatives",
  "stake-originals-games",
  "nfl-betting",
  "nba-betting",
  "ufc-betting",
  "soccer-betting",
  "tennis-betting",
  "boxing-betting",
  "f1-betting",
  "peer-to-peer-sports-betting",
  "betting-exchange-explained",
  "matched-betting",
  "cash-out-betting",
  "prop-bets-explained",
  "no-kyc-sportsbook",
  "minecraft-gambling",
  "mystery-box-site",
  "valve-gambling-lawsuit",
  "deposit-match-bonus",
  "casino-referral-bonus",
  "reload-bonus-casino",
  "casino-comps",
  "crypto-casino-affiliate-program",
  "malta-gaming-authority-license",
  "gambling-tax-uk",
  "gasless-transactions",
  "account-abstraction-wallet",
  "ton-wallet",
  "pai-gow-poker",
  "casino-war-game",
  "sic-bo-online",
  "penny-slots-online",
  "high-limit-slots",
  "blackjack-tournaments",
  "heads-up-poker-strategy",
  "polymarket-vs-kalshi",
]);

for (const g of NEW_GUIDES) PLANNED.add(g.slug);

let fail = 0;
const err = (m: string) => {
  fail++;
  console.log("  FAIL " + m);
};
const slugs = new Set<string>(),
  kws = new Set<string>();
for (const g of GUIDES) {
  const wc = wordCount(g);
  console.log(`${g.slug}: ${wc} words, title ${g.title.length}, desc ${g.description.length}`);
  if (wc < 1850 || wc > 2400) err(`word count ${wc}`);
  if (g.title.length < 40 || g.title.length > 59) err(`title length ${g.title.length}`);
  if (g.description.length < 120 || g.description.length > 159)
    err(`desc length ${g.description.length}`);
  if (slugs.has(g.slug)) err("duplicate slug");
  slugs.add(g.slug);
  if (kws.has(g.keyword)) err("duplicate keyword");
  kws.add(g.keyword);
  if (!PLANNED.has(g.slug)) err("slug not in plan");
  if (g.faqs.length < 4 || g.faqs.length > 6) err(`faqs ${g.faqs.length}`);
  const first100 = [g.h1, g.answer].join(" ").toLowerCase().split(/\s+/).slice(0, 100).join(" ");
  if (!first100.includes(g.keyword.toLowerCase())) err("keyword missing from first 100 words");
  const body = [
    g.answer,
    ...g.facts,
    ...g.sections.map((s) => s.body),
    ...g.faqs.map((f) => `${f.q}\n${f.a}`),
    g.cta?.primary.to ?? "",
    g.cta?.secondary.to ?? "",
  ].join("\n");
  const links = [...body.matchAll(/\]\((\/[^)\s]*)\)/g)].map(
    (m) => m[1].split("#")[0].split("?")[0].replace(/\/$/, "") || "/",
  );
  if (g.cta)
    links.push(
      g.cta.primary.to.split("#")[0].split("?")[0],
      g.cta.secondary.to.split("#")[0].split("?")[0],
    );
  const publishedTopicsSet = new Set(publishedTopics().map((t) => t.slug));
  const topicLinks = links.filter((l) => l.startsWith("/guides/topics/"));
  const guideLinks = links.filter(
    (l) => l.startsWith("/guides/") && !l.startsWith("/guides/topics/") && l !== "/guides",
  );
  const siteLinks = links.filter((l) => !l.startsWith("/guides/") && l !== "/guides");
  for (const l of guideLinks)
    if (!getGuide(l.slice("/guides/".length))) err(`unknown guide link ${l}`);
  for (const l of topicLinks)
    if (!publishedTopicsSet.has(l.slice("/guides/topics/".length))) err(`unknown topic link ${l}`);
  for (const l of siteLinks) if (!STATIC.has(l)) err(`unknown site link ${l}`);
  const sectionGuideLinks = g.sections.flatMap((s) =>
    [...s.body.matchAll(/\]\((\/guides\/(?!topics\/)[^)\s#?]*)/g)].map((m) => m[1]),
  );
  if (new Set(sectionGuideLinks).size < 3)
    err(`only ${new Set(sectionGuideLinks).size} guide links`);
  if (!g.sections.some((s) => s.body.includes("/guides/topics/"))) err("no topic hub link");
  if (!g.sections.some((s) => /\]\((\/(?!guides\/)[^)]*)\)/.test(s.body))) err("no site links");
  for (const r of g.related) if (!getGuide(r)) err(`unknown related ${r}`);
}
console.log(fail ? `\n${fail} problem(s)` : `\nAll ${GUIDES.length} guides pass.`);
process.exit(fail ? 1 : 0);
