import type { GuideCluster } from "../src/content/guides/types";

/** Planned guides from the Semrush batch (2026-09). Scope notes keep each page off an existing page's intent. */
export type PlannedGuide = {
  slug: string;
  cluster: GuideCluster;
  group: string;
  keyword: string;
  scope: string;
  batch: number;
};

const p = (
  batch: number,
  cluster: GuideCluster,
  group: string,
  slug: string,
  keyword: string,
  scope: string,
): PlannedGuide => ({ slug, cluster, group, keyword, scope, batch });

export const NEW_GUIDES: PlannedGuide[] = [
  // 1 — probability and paradoxes
  p(
    1,
    "Casino knowledge",
    "Probability and paradoxes",
    "law-of-large-numbers-gambling",
    "law of large numbers",
    "Why the house wins over volume; convergence of results to expectation. house-edge keeps the definition; link it.",
  ),
  p(
    1,
    "Casino knowledge",
    "Probability and paradoxes",
    "monty-hall-problem",
    "monty hall problem",
    "The puzzle, the 2/3 proof, simulations, and what it teaches about conditional probability for gamblers.",
  ),
  p(
    1,
    "Casino knowledge",
    "Probability and paradoxes",
    "regression-to-the-mean-gambling",
    "regression to the mean",
    "Streaks returning to average; hot tables, sports form. gamblers-fallacy keeps the independence mistake; link it.",
  ),
  p(
    1,
    "Casino knowledge",
    "Probability and paradoxes",
    "st-petersburg-paradox",
    "st petersburg paradox",
    "Infinite expected value, utility, finite bankrolls; tie to martingale-strategy and expected-value-gambling.",
  ),
  p(
    1,
    "Games & odds",
    "Systems and strategy",
    "risk-of-ruin",
    "risk of ruin",
    "The math concept and formula (gambler's ruin). bankroll-calculator stays the tool; blackjack-simulator keeps blackjack sims.",
  ),
  p(
    1,
    "Games & odds",
    "Systems and strategy",
    "labouchere-system",
    "labouchere system",
    "Cancellation system, worked lines, why it fails. dalembert-strategy only mentions it; link across.",
  ),
  p(
    1,
    "Games & odds",
    "Systems and strategy",
    "flat-betting",
    "flat betting",
    "Constant stake as a system; compare to progressions; bankroll longevity.",
  ),
  // 2 — psychology
  p(
    2,
    "Casino knowledge",
    "Psychology of gambling",
    "sunk-cost-fallacy-gambling",
    "sunk cost fallacy",
    "The bias in general and in gambling (chasing). how-to-stop-gambling keeps recovery steps.",
  ),
  p(
    2,
    "Casino knowledge",
    "Psychology of gambling",
    "loss-aversion-gambling",
    "loss aversion",
    "Kahneman-Tversky loss aversion and prospect theory applied to betting decisions.",
  ),
  p(
    2,
    "Casino knowledge",
    "Psychology of gambling",
    "illusion-of-control",
    "illusion of control",
    "Langer's research; dice throwing, picking numbers, stop buttons. gamblers-fallacy is a different bias.",
  ),
  p(
    2,
    "Casino knowledge",
    "Psychology of gambling",
    "skinner-box-slot-machines",
    "skinner box",
    "Operant conditioning and variable-ratio reward schedules (fold 'variable ratio reinforcement' in here). why-is-gambling-addictive keeps the addiction angle.",
  ),
  p(
    2,
    "Casino knowledge",
    "Psychology of gambling",
    "gambling-statistics",
    "gambling statistics",
    "Participation, market size, problem-gambling prevalence; cite sources with years, no invented numbers.",
  ),
  p(
    2,
    "Casino knowledge",
    "Culture and belief",
    "is-gambling-a-sin",
    "is gambling a sin",
    "Respectful, neutral overview of Christian denominations' views; not preaching.",
  ),
  p(
    2,
    "Casino knowledge",
    "Culture and belief",
    "gambling-in-islam",
    "gambling in islam",
    "Maysir, Quranic references, scholarly positions; respectful and neutral.",
  ),
  // 3 — legends I
  p(
    3,
    "Casino knowledge",
    "Famous gamblers",
    "famous-gamblers",
    "famous gamblers",
    "Hub-style overview of famous gamblers with short profiles linking to each person's page.",
  ),
  p(
    3,
    "Casino knowledge",
    "Famous gamblers",
    "phil-ivey",
    "phil ivey",
    "Poker career, edge-sorting cases (Crockfords, Borgata), lessons. Only well documented facts.",
  ),
  p(
    3,
    "Casino knowledge",
    "Famous gamblers",
    "edward-thorp",
    "edward thorp",
    "Beat the Dealer, card counting origin, Kelly, wearable computer, later finance.",
  ),
  p(
    3,
    "Casino knowledge",
    "Famous gamblers",
    "mit-blackjack-team",
    "mit blackjack team",
    "History, team play (spotters, big players), Bringing Down the House vs reality.",
  ),
  p(
    3,
    "Casino knowledge",
    "Famous gamblers",
    "ken-uston",
    "ken uston",
    "Team play, Griffin Investigations, Uston v. Resorts International (New Jersey ruling).",
  ),
  p(
    3,
    "Casino knowledge",
    "Famous gamblers",
    "don-johnson-blackjack",
    "don johnson blackjack",
    "2011 Atlantic City run, negotiated rules/loss rebates. Distinct from blackjack-basic-strategy.",
  ),
  p(
    3,
    "Casino knowledge",
    "Famous gamblers",
    "kerry-packer",
    "kerry packer",
    "Australian media owner, legendary high-roller stories; flag which stories are anecdotal.",
  ),
  // 4 — legends II
  p(
    4,
    "Casino knowledge",
    "Famous gamblers",
    "doyle-brunson",
    "doyle brunson",
    "Texas Dolly, WSOP titles, Super/System; died 2023.",
  ),
  p(
    4,
    "Casino knowledge",
    "Famous gamblers",
    "stu-ungar",
    "stu ungar",
    "Three WSOP Main Events, gin rummy, addiction and death in 1998; handle respectfully.",
  ),
  p(
    4,
    "Casino knowledge",
    "Famous gamblers",
    "chris-moneymaker",
    "chris moneymaker",
    "2003 WSOP Main Event from an online satellite; the 'Moneymaker effect'.",
  ),
  p(
    4,
    "Casino knowledge",
    "Famous gamblers",
    "billy-walters",
    "billy walters",
    "Sports bettor, Computer Group, 2017 insider-trading conviction, commuted 2021. how-to-win-at-sports-betting keeps strategy.",
  ),
  p(
    4,
    "Casino knowledge",
    "Famous gamblers",
    "archie-karas",
    "archie karas",
    "The Run (1992–1995) from ~$50 to ~$40M and losing it; risk of ruin lesson.",
  ),
  p(
    4,
    "Casino knowledge",
    "Famous gamblers",
    "tommy-glenn-carmichael",
    "tommy glenn carmichael",
    "Slot cheat, the 'monkey paw' and light wand devices; how surveillance and regulation responded.",
  ),
  p(
    4,
    "Casino knowledge",
    "Famous gamblers",
    "trainwreckstv-gambling",
    "trainwreckstv",
    "Streamer's gambling streams, Stake ties, the 2022 Twitch policy debate. kick-gambling-streamers and twitch-slots-ban keep platform policy.",
  ),
  // 5 — history and places
  p(
    5,
    "Casino knowledge",
    "History and places",
    "history-of-gambling",
    "history of gambling",
    "Ancient dice to online/crypto; include slot machine and blackjack history. csgo-gambling-history keeps the skin era.",
  ),
  p(
    5,
    "Casino knowledge",
    "History and places",
    "history-of-poker",
    "history of poker",
    "Poque/As-Nas origins, riverboats, WSOP, the online boom.",
  ),
  p(
    5,
    "Casino knowledge",
    "History and places",
    "las-vegas-history",
    "las vegas history",
    "1905 founding, 1931 legalization, mob era, corporate era, Strip today.",
  ),
  p(
    5,
    "Casino knowledge",
    "History and places",
    "stardust-casino",
    "stardust casino",
    "Stardust Resort history 1958–2006, mob skimming, Casino film link, implosion 2007.",
  ),
  p(
    5,
    "Casino knowledge",
    "History and places",
    "oldest-casino",
    "oldest casino",
    "Casino di Venezia (1638 Ridotto), Baden-Baden, Monte Carlo, US oldest.",
  ),
  p(
    5,
    "Casino knowledge",
    "History and places",
    "gambling-movies",
    "gambling movies",
    "Curated list with what each film gets right or wrong about odds (include casino movies).",
  ),
  p(
    5,
    "Casino knowledge",
    "History and places",
    "gambling-quotes",
    "gambling quotes",
    "Attributed quotes with context; mark misattributions; no fabricated quotes.",
  ),
  // 6 — casino floor and operations
  p(
    6,
    "Casino knowledge",
    "Inside the casino",
    "casino-etiquette",
    "casino etiquette",
    "Table manners, tipping, phones, chips. live-dealer-casino keeps online live tables.",
  ),
  p(
    6,
    "Casino knowledge",
    "Inside the casino",
    "casino-dress-code",
    "casino dress code",
    "What casinos expect by venue type and region; Monte Carlo vs Vegas.",
  ),
  p(
    6,
    "Casino knowledge",
    "Inside the casino",
    "casino-chip-values",
    "casino chip values",
    "Chip colors and denominations, regional variation, casino tokens, counterfeit controls.",
  ),
  p(
    6,
    "Casino knowledge",
    "Inside the casino",
    "casino-carpet",
    "casino carpet",
    "Why casino carpets are busy; design history; myth vs evidence.",
  ),
  p(
    6,
    "Casino knowledge",
    "Inside the casino",
    "casino-surveillance",
    "casino surveillance",
    "Eye in the sky, surveillance vs security, facial recognition, cheating detection.",
  ),
  p(
    6,
    "Casino knowledge",
    "Inside the casino",
    "casino-cage",
    "casino cage",
    "The cashier cage: chips to cash, markers, CTRs, why cashouts take time. casino-withdrawal-pending keeps online cashouts.",
  ),
  p(
    6,
    "Casino knowledge",
    "Inside the casino",
    "casino-marker",
    "casino marker",
    "Casino credit lines, how markers work, legal consequences of unpaid markers.",
  ),
  // 7 — casino jobs
  p(
    7,
    "Casino knowledge",
    "Casino jobs",
    "pit-boss",
    "pit boss",
    "Role of the pit boss/floor supervisor in the hierarchy; mention croupier only as a term that links to dealer-school.",
  ),
  p(
    7,
    "Casino knowledge",
    "Casino jobs",
    "dealer-school",
    "dealer school",
    "How to become a casino dealer or croupier: schools, auditions, licensing.",
  ),
  p(
    7,
    "Casino knowledge",
    "Casino jobs",
    "casino-dealer-salary",
    "casino dealer salary",
    "Base pay plus tokes, variation by venue and country; cite BLS where possible.",
  ),
  p(
    7,
    "Casino knowledge",
    "Casino jobs",
    "casino-host",
    "casino host",
    "What hosts do, how players get one, theoretical loss. vip-casino-programs keeps tiers.",
  ),
  p(
    7,
    "Casino knowledge",
    "Culture and belief",
    "biggest-casino-wins",
    "biggest casino wins",
    "Documented record jackpots (Megabucks 2003 etc.) with sources; survivor bias lesson.",
  ),
  p(
    7,
    "Casino knowledge",
    "Culture and belief",
    "casino-royale-poker",
    "casino royale poker",
    "The 2006 film's poker scenes, the hands, realism, vs baccarat in the novel.",
  ),
  p(
    7,
    "Casino knowledge",
    "Probability and paradoxes",
    "how-to-shuffle-cards",
    "how to shuffle cards",
    "Riffle, overhand, bridge, table wash; seven riffles result (Bayer–Diaconis). rng pages keep digital randomness.",
  ),
  // 8 — poker extras + card basics
  p(
    8,
    "Poker",
    "Strategy",
    "poker-math",
    "poker math",
    "Combinatorics, equity, EV, rule of 2 and 4, ICM basics. poker-pot-odds keeps pot odds; link it.",
  ),
  p(
    8,
    "Poker",
    "Learn the game",
    "poker-slang",
    "poker slang",
    "Poker-only jargon glossary. casino-terminology keeps general casino vocabulary.",
  ),
  p(
    8,
    "Poker",
    "Variants and money",
    "deuces-wild",
    "deuces wild",
    "Deuces Wild video poker paytables (full pay ~100.76%), strategy basics. video-poker-paytables keeps Jacks or Better.",
  ),
  p(
    8,
    "Blackjack",
    "Rules",
    "is-card-counting-illegal",
    "is card counting illegal",
    "Legality and casino countermeasures only (backoffs, trespass, devices). card-counting keeps the how-to.",
  ),
  p(
    8,
    "Games of chance",
    "Cards and decks",
    "52-card-deck",
    "52 card deck",
    "Composition, suits, history, probabilities of common draws.",
  ),
  p(
    8,
    "Casino games",
    "Table games",
    "teen-patti",
    "teen patti",
    "Rules, hand rankings, blind/seen play, odds.",
  ),
  p(
    8,
    "Casino games",
    "Table games",
    "pai-gow-tiles",
    "pai gow tiles",
    "Chinese domino version: tiles, pairs, setting hands. pai-gow-poker keeps the card game.",
  ),
  // 9 — blackjack variants
  p(
    9,
    "Blackjack",
    "Variants",
    "free-bet-blackjack",
    "free bet blackjack",
    "Free doubles and splits, dealer 22 push, house edge.",
  ),
  p(
    9,
    "Blackjack",
    "Variants",
    "spanish-21",
    "spanish 21",
    "No tens, liberal rules, bonus 21s, edge.",
  ),
  p(
    9,
    "Blackjack",
    "Variants",
    "blackjack-switch",
    "blackjack switch",
    "Swap top cards, dealer 22 push, edge.",
  ),
  p(
    9,
    "Blackjack",
    "Variants",
    "infinite-blackjack",
    "infinite blackjack",
    "Evolution's Infinite Blackjack live game: shared hand, six-card Charlie, side bets. how-many-decks-blackjack keeps infinite-deck maths.",
  ),
  p(
    9,
    "Blackjack",
    "Decisions",
    "blackjack-side-bets",
    "blackjack side bets",
    "Perfect Pairs, 21+3, Lucky Ladies, Bust It; edges. blackjack-insurance keeps insurance.",
  ),
  p(
    9,
    "Games & odds",
    "Other casino games",
    "crypto-baccarat",
    "crypto baccarat",
    "Where/how to play baccarat with crypto (commercial). baccarat-rules keeps rules and odds.",
  ),
  p(
    9,
    "Games & odds",
    "Other casino games",
    "crypto-keno",
    "crypto keno",
    "Playing keno with crypto (commercial). keno-odds and keno-strategy keep maths.",
  ),
  // 10 — table games
  p(
    10,
    "Casino games",
    "Table games",
    "craps-strategy",
    "craps strategy",
    "Betting strategy: pass/come with odds, avoid props. craps-odds and online-craps keep odds and where to play.",
  ),
  p(
    10,
    "Casino games",
    "Table games",
    "baccarat-strategy",
    "baccarat strategy",
    "Banker bet, avoiding tie, pattern myths, bankroll. baccarat-rules keeps rules.",
  ),
  p(
    10,
    "Casino games",
    "Table games",
    "french-roulette",
    "french roulette",
    "La partage, en prison, French layout and call bets. roulette-odds-chart keeps charts.",
  ),
  p(
    10,
    "Casino games",
    "Table games",
    "sic-bo-strategy",
    "sic bo strategy",
    "Which sic bo bets are least bad, bankroll. sic-bo-online keeps the game overview.",
  ),
  p(
    10,
    "Casino games",
    "Table games",
    "dragon-tiger",
    "dragon tiger",
    "Rules, tie bet, suited tie, edge.",
  ),
  p(
    10,
    "Game shows",
    "Live game shows",
    "lightning-roulette",
    "lightning roulette",
    "Evolution Lightning Roulette multipliers, 29:1 straight pay, RTP.",
  ),
  p(
    10,
    "Games of chance",
    "Tiles and mahjong",
    "mahjong-gambling",
    "mahjong gambling",
    "Mahjong played for money: scoring stakes, parlours, Macau/HK context. mahjong-tiles keeps tile rules.",
  ),
  // 11 — live game shows
  p(
    11,
    "Game shows",
    "Live game shows",
    "crazy-time",
    "crazy time",
    "Evolution Crazy Time wheel, bonus games, RTP by segment, stats trackers (fold crazy time stats here).",
  ),
  p(
    11,
    "Game shows",
    "Live game shows",
    "dream-catcher-game",
    "dream catcher",
    "Evolution Dream Catcher money wheel, segments, multipliers, RTP. wheel-of-fortune-casino-game keeps generic money wheels.",
  ),
  p(
    11,
    "Game shows",
    "Live game shows",
    "monopoly-live",
    "monopoly live",
    "Evolution Monopoly Live wheel, 2 rolls/4 rolls bonus, RTP.",
  ),
  p(
    11,
    "Game shows",
    "Live game shows",
    "funky-time",
    "funky time",
    "Evolution Funky Time letters wheel and bonus games, RTP.",
  ),
  p(
    11,
    "Game shows",
    "Crash and instant games",
    "jetx-game",
    "jetx",
    "SmartSoft JetX crash game, RTP, auto cashout. crash-gambling keeps generic crash.",
  ),
  p(
    11,
    "Game shows",
    "Crash and instant games",
    "spaceman-game",
    "spaceman game",
    "Pragmatic Play Spaceman crash game, 50% cashout feature, RTP.",
  ),
  p(
    11,
    "Game shows",
    "Crash and instant games",
    "chicken-road-game",
    "chicken road game",
    "InOut Games Chicken Road step game, difficulty levels, RTP; scam-app warnings.",
  ),
  // 12 — crypto payments I
  p(
    12,
    "Crypto payments",
    "Stablecoins",
    "what-is-tether",
    "what is tether",
    "Tether/USDT explained: issuer, reserves, attestations, chains. usdt-casino keeps casino use; usdc-vs-usdt keeps comparison.",
  ),
  p(
    12,
    "Crypto payments",
    "Deposits and cashouts",
    "how-to-buy-usdt",
    "how to buy usdt",
    "Buying USDT on exchanges/apps, choosing a network. erc20-vs-trc20 keeps network standards.",
  ),
  p(
    12,
    "Crypto payments",
    "Deposits and cashouts",
    "how-to-buy-solana",
    "how to buy solana",
    "Buying SOL, wallets, fees. solana-casino keeps gambling use.",
  ),
  p(
    12,
    "Crypto payments",
    "Deposits and cashouts",
    "cash-app-bitcoin",
    "cash app bitcoin",
    "Buying, sending and withdrawing bitcoin on Cash App, limits, fees.",
  ),
  p(
    12,
    "Crypto payments",
    "Deposits and cashouts",
    "buy-crypto-with-paypal",
    "buy crypto with paypal",
    "PayPal crypto, PYUSD, transfers out, fees. buy-crypto-with-card keeps card purchases.",
  ),
  p(
    12,
    "Crypto payments",
    "Networks and fees",
    "bitcoin-fees",
    "bitcoin fees",
    "Bitcoin network fees: sat/vB, mempool, RBF/CPFP. gas-fees-explained keeps EVM gas; crypto-casino-deposit-fees keeps casino costs.",
  ),
  p(
    12,
    "Crypto payments",
    "Networks and fees",
    "bitcoin-cash-casino",
    "bitcoin cash casino",
    "Gambling with BCH: fees, confirmations, availability.",
  ),
  // 13 — crypto payments II + tech
  p(
    13,
    "Crypto payments",
    "Wallets",
    "exodus-wallet",
    "exodus wallet",
    "Exodus wallet review: features, security model, fees.",
  ),
  p(
    13,
    "Crypto payments",
    "Wallets",
    "multisig-wallet",
    "multisig wallet",
    "m-of-n wallets, Safe, use cases; self-custody-wallet keeps single-key custody.",
  ),
  p(
    13,
    "Crypto payments",
    "Deposits and cashouts",
    "crypto-debit-card",
    "crypto debit card",
    "Cards that spend crypto (not buying crypto with a card, which buy-crypto-with-card covers).",
  ),
  p(
    13,
    "Crypto payments",
    "Ops and extras",
    "bitcoin-faucet",
    "bitcoin faucet",
    "What faucets are, earnings reality, scams; include crypto faucet as secondary.",
  ),
  p(
    13,
    "Provably fair",
    "How fairness works",
    "zero-knowledge-proof-gambling",
    "zero knowledge proof",
    "ZK proofs explained plainly and their use in privacy and gaming. provably-fair-casino keeps fairness verification.",
  ),
  p(
    13,
    "Game shows",
    "Crash and instant games",
    "mines-predictor",
    "mines predictor",
    "Do mines predictor apps/bots work? Scam warning only. mines-game-strategy keeps gameplay.",
  ),
  p(
    13,
    "Games of chance",
    "Luck and lotteries",
    "quick-pick-lottery",
    "quick pick",
    "Quick pick vs own numbers, odds identical, split-jackpot effect.",
  ),
  // 14 — card games for money I
  p(
    14,
    "Games of chance",
    "Card games",
    "how-to-play-spades",
    "how to play spades",
    "Spades rules, bidding, nil, scoring; playing for stakes. Adults only for money.",
  ),
  p(
    14,
    "Games of chance",
    "Card games",
    "how-to-play-rummy",
    "how to play rummy",
    "Basic rummy rules, melds, variants. how-to-play-gin-rummy keeps gin.",
  ),
  p(
    14,
    "Games of chance",
    "Card games",
    "how-to-play-gin-rummy",
    "how to play gin rummy",
    "Gin rummy rules, knocking, undercut, scoring, playing for money.",
  ),
  p(
    14,
    "Games of chance",
    "Card games",
    "canasta-rules",
    "canasta rules",
    "Canasta rules, melds, canastas, scoring.",
  ),
  p(
    14,
    "Games of chance",
    "Card games",
    "how-to-play-euchre",
    "how to play euchre",
    "Euchre rules, trump, bowers, scoring.",
  ),
  p(
    14,
    "Games of chance",
    "Card games",
    "oh-hell-card-game",
    "oh hell card game",
    "Oh Hell rules, bidding exact tricks, scoring.",
  ),
  p(
    14,
    "Games of chance",
    "Card games",
    "pitch-card-game",
    "pitch card game",
    "Pitch rules, high/low/jack/game, scoring.",
  ),
  // 15 — card games for money II + street games
  p(
    15,
    "Games of chance",
    "Card games",
    "31-card-game",
    "31 card game",
    "Scat/31 rules, knocking, lives, playing for quarters.",
  ),
  p(
    15,
    "Games of chance",
    "Card games",
    "bourre-card-game",
    "bourre card game",
    "Bourré rules, trick-taking, pot mechanics, strategy.",
  ),
  p(
    15,
    "Games of chance",
    "Street and hustle games",
    "three-card-monte",
    "three card monte",
    "The con: shills, sleight of hand; why you cannot win. fake-casino-sites for online equivalents.",
  ),
  p(
    15,
    "Games of chance",
    "Street and hustle games",
    "carnival-games",
    "carnival games",
    "Are carnival games rigged? Physics and odds of common games.",
  ),
  p(
    15,
    "Games of chance",
    "Street and hustle games",
    "claw-machine-tricks",
    "claw machine tricks",
    "Claw strength payout settings, are they rigged, odds.",
  ),
  p(
    15,
    "Games of chance",
    "Street and hustle games",
    "penny-pitching",
    "penny pitching",
    "Pitching pennies rules and history; coin-flip-for-money keeps coin flipping.",
  ),
  p(
    15,
    "Games of chance",
    "Luck and lotteries",
    "pull-tabs",
    "pull tabs",
    "Pull tab tickets, how deals are printed, odds and payout percentages. crypto-scratch-cards keeps online scratchers.",
  ),
  // 16 — dice games
  p(
    16,
    "Games of chance",
    "Dice games",
    "farkle-rules",
    "farkle rules",
    "Farkle rules, scoring table, odds of farkling, strategy.",
  ),
  p(
    16,
    "Games of chance",
    "Dice games",
    "yahtzee-rules",
    "yahtzee rules",
    "Yahtzee rules, scorecard, probabilities.",
  ),
  p(
    16,
    "Games of chance",
    "Dice games",
    "liars-dice",
    "liars dice",
    "Liar's dice rules, bidding, probability of a bid.",
  ),
  p(
    16,
    "Games of chance",
    "Dice games",
    "bunco-rules",
    "bunco",
    "Bunco rules, rounds, scoring, party setup (primary keyword 'bunco'; 'bunco rules' as secondary).",
  ),
  p(
    16,
    "Games of chance",
    "Dice games",
    "shut-the-box",
    "shut the box",
    "Shut the box rules, odds, best strategy.",
  ),
  p(
    16,
    "Games of chance",
    "Dice games",
    "left-right-center-rules",
    "left right center rules",
    "LCR rules, chip flow, odds of winning by seat.",
  ),
  p(
    16,
    "Games of chance",
    "Dice games",
    "ship-captain-crew",
    "ship captain crew",
    "Ship captain crew rules, odds of qualifying.",
  ),
  // 17 — dice games II
  p(
    17,
    "Games of chance",
    "Dice games",
    "poker-dice",
    "poker dice",
    "Poker dice rules and hand odds.",
  ),
  p(
    17,
    "Games of chance",
    "Dice games",
    "cee-lo-rules",
    "cee lo rules",
    "Cee-lo (4-5-6) rules, banker vs player, odds. dice-duel-game keeps PvP dice.",
  ),
  p(
    17,
    "Games of chance",
    "Dice games",
    "chuck-a-luck",
    "chuck a luck",
    "Birdcage game, house edge ~7.87%, relation to sic bo.",
  ),
  p(
    17,
    "Games of chance",
    "Dice games",
    "hazard-dice-game",
    "hazard dice game",
    "Medieval hazard rules, main and chance, how it became craps.",
  ),
  p(
    17,
    "Games of chance",
    "Dice games",
    "mexico-dice-game",
    "mexico dice game",
    "Mexico dice rules, scoring order, lives.",
  ),
  p(
    17,
    "Games of chance",
    "Luck and lotteries",
    "lucky-numbers-gambling",
    "lucky number",
    "Lucky numbers across cultures (7, 8, 4); why numbers do not change odds.",
  ),
  p(
    17,
    "Games of chance",
    "Luck and lotteries",
    "lucky-colors-gambling",
    "lucky colors",
    "Lucky colors across cultures (red, gold, green); roulette-colors keeps wheel colours.",
  ),
  // 18 — board and tile games
  p(
    18,
    "Games of chance",
    "Board games",
    "backgammon-rules",
    "backgammon rules",
    "Setup, movement, hitting, bearing off, doubling cube basics.",
  ),
  p(
    18,
    "Games of chance",
    "Board games",
    "backgammon-strategy",
    "backgammon strategy",
    "Opening moves, priming, blitz, doubling cube decisions.",
  ),
  p(
    18,
    "Games of chance",
    "Board games",
    "tavla",
    "tavla",
    "Turkish backgammon rules and differences.",
  ),
  p(
    18,
    "Games of chance",
    "Board games",
    "checkers-rules",
    "checkers rules",
    "Official checkers rules, kings, forced captures; playing for stakes.",
  ),
  p(
    18,
    "Games of chance",
    "Tiles and mahjong",
    "mahjong-tiles",
    "mahjong tiles",
    "Tile set, suits, honours, meanings, basic rules (mahjong rules as secondary).",
  ),
  p(
    18,
    "Games of chance",
    "Tiles and mahjong",
    "dominoes-rules",
    "dominoes rules",
    "Block and draw dominoes, scoring; hub for domino variants.",
  ),
  p(
    18,
    "Games of chance",
    "Tiles and mahjong",
    "mexican-train-rules",
    "mexican train rules",
    "Mexican train dominoes rules and scoring.",
  ),
  // 19 — tiles, bingo, pachislot, pools
  p(
    19,
    "Games of chance",
    "Tiles and mahjong",
    "chicken-foot-dominoes",
    "chicken foot dominoes",
    "Chicken foot rules and scoring.",
  ),
  p(
    19,
    "Games of chance",
    "Tiles and mahjong",
    "texas-42-dominoes",
    "texas 42 dominoes",
    "Texas 42 rules, bidding, trumps.",
  ),
  p(
    19,
    "Games of chance",
    "Luck and lotteries",
    "bingo-patterns",
    "bingo patterns",
    "Common bingo patterns and how pattern choice changes game length. crypto-bingo keeps online bingo.",
  ),
  p(
    19,
    "Games of chance",
    "Luck and lotteries",
    "bingo-caller",
    "bingo caller",
    "How to call bingo, calls list and nicknames.",
  ),
  p(
    19,
    "Games of chance",
    "Luck and lotteries",
    "pachislot",
    "pachislot",
    "Japanese pachislot machines, skill stop, settings 1–6. pachinko-odds keeps pachinko.",
  ),
  p(
    19,
    "Games of chance",
    "Luck and lotteries",
    "survivor-pool",
    "survivor pool",
    "NFL survivor pool rules and strategy. nfl-betting keeps sportsbook betting.",
  ),
  p(
    19,
    "Games of chance",
    "Luck and lotteries",
    "handicapping-horses",
    "handicapping horses",
    "Speed figures, class, pace, form. crypto-horse-racing-betting keeps crypto betting.",
  ),
  // 20 — luck, party, plinko board
  p(
    20,
    "Games of chance",
    "Luck and lotteries",
    "horseshoe-luck",
    "horseshoe luck",
    "Horseshoe superstition: up or down, history.",
  ),
  p(
    20,
    "Games of chance",
    "Street and hustle games",
    "plinko-board",
    "plinko board",
    "The physical Plinko board (The Price Is Right, DIY boards, physics). plinko-gambling keeps online plinko.",
  ),
  p(
    20,
    "Games of chance",
    "Street and hustle games",
    "casino-party-ideas",
    "casino party ideas",
    "Casino night party planning, play money, legality of charity nights.",
  ),
  // 21 — card rules (skipped pages that repeat an existing guide: zilch, spit, cheat, card suits, joker, degen, roulette history, bar dice)
  p(
    21,
    "Games of chance",
    "Card games",
    "go-fish-rules",
    "go fish rules",
    "Go Fish books and asking. Distinct from rummy.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "phase-10-rules",
    "phase 10 rules",
    "Mattel Phase 10 phases, skips, and scoring.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "speed-card-game",
    "speed card game",
    "Speed, and the same game called Spit or Slam. One page.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "cribbage-rules",
    "cribbage rules",
    "Pegging, the crib, and the 121 board.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "skip-bo-rules",
    "skip-bo rules",
    "Skip-Bo stock piles and building 1 to 12.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "trash-card-game",
    "trash card game",
    "Trash and Garbage are the same race-down game.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "old-maid-card-game",
    "old maid card game",
    "Children's pairing game with one odd queen.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "golf-card-game-rules",
    "golf card game",
    "Six-card golf, lowest score, with nine-card as a variant.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "solitaire-rules",
    "solitaire rules",
    "Klondike solitaire. Freecell and Spider named only.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "hearts-card-game-rules",
    "hearts card game",
    "Four-player hearts, queen of spades, shoot the moon.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "crazy-eights-rules",
    "crazy eights rules",
    "Match suit or rank, eights wild.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "sequence-rules",
    "sequence rules",
    "Jax Sequence board, chips, one-eyed and two-eyed jacks.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "war-card-game-rules",
    "war card game",
    "Home card game War. casino-war-game keeps the table game.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "pinochle-rules",
    "pinochle rules",
    "Partnership pinochle melds and tricks.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "palace-card-game",
    "palace card game",
    "Palace, also called Shithead. Shedding with down-cards.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "bs-card-game-rules",
    "bs card game",
    "BS, Bullshit, and Cheat are the same game. One page.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "tonk-card-game",
    "tonk card game",
    "Five-card tonk, deadwood, and knocking.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "double-solitaire",
    "double solitaire",
    "Shared-foundation Klondike race. Not Spite and Malice.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "kings-corner-rules",
    "kings corner rules",
    "Kings in the corner layout and foundations.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "nertz-rules",
    "nertz rules",
    "Multiplayer solitaire race, also Nerts or Pounce.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "slapjack-rules",
    "slapjack rules",
    "Slap the jack. Children's game.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "president-card-game-rules",
    "president card game",
    "President shedding and the card exchange. Also called Scum.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "scopa-rules",
    "scopa rules",
    "Italian capturing game, scopa, primiera, sette bello.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "egyptian-ratscrew-rules",
    "egyptian ratscrew",
    "Slap doubles, sandwiches, and jacks.",
  ),
  p(
    21,
    "Games of chance",
    "Card games",
    "briscola-rules",
    "briscola rules",
    "Italian trump game, ace and three as point cards.",
  ),
  p(
    21,
    "Games of chance",
    "Dice games",
    "pig-dice-game",
    "pig dice game",
    "One-die Pig to 100. Not Pass the Pigs. Not Farkle.",
  ),
  p(
    21,
    "Games of chance",
    "Dice games",
    "tenzi-rules",
    "tenzi rules",
    "Ten-dice race to a matching set.",
  ),
  p(
    21,
    "Games of chance",
    "Dice games",
    "horse-race-dice-game",
    "horse race dice",
    "Party dice horses 2 through 12. Not a sportsbook.",
  ),
  p(
    21,
    "Casino knowledge",
    "Inside the casino",
    "marked-cards",
    "marked cards",
    "What marked cards are and how to leave. No marking method.",
  ),
  p(
    21,
    "Casino knowledge",
    "Inside the casino",
    "punch-board-gambling",
    "punch board gambling",
    "Historical punchboards. pull-tabs stays the later cousin.",
  ),
  p(
    21,
    "Casino knowledge",
    "Inside the casino",
    "hole-carding",
    "hole carding",
    "Seeing the dealer's downcard. Not Texas Hold'em hole cards. No peek method.",
  ),
  p(
    21,
    "Casino knowledge",
    "Inside the casino",
    "past-posting",
    "past posting",
    "Late bets after the outcome. Fraud. No method.",
  ),
  p(
    21,
    "Casino knowledge",
    "Inside the casino",
    "casino-architecture",
    "casino architecture",
    "Floor plan, cage, sightlines. casino-carpet keeps carpet patterns.",
  ),
  p(
    21,
    "Casino knowledge",
    "History and places",
    "riviera-casino",
    "riviera casino",
    "Las Vegas Strip Riviera, 1955–2015. Not the Stardust.",
  ),
  p(
    21,
    "Casino knowledge",
    "History and places",
    "history-of-dice",
    "history of dice",
    "Astragali to casino dice. history-of-gambling stays the broad history.",
  ),
  p(
    21,
    "Casino knowledge",
    "History and places",
    "casino-black-book",
    "casino black book",
    "Nevada List of Excluded Persons. Not a card-counter backoff.",
  ),
  p(
    21,
    "Slots",
    "Maths and features",
    "loose-slots",
    "loose slots",
    "What players mean by a loose slot. slot-machine-odds keeps the maths.",
  ),
  // 22 — avalanche batch, cannibalizing slugs omitted
  p(
    22,
    "Sports betting",
    "Bet types",
    "betting-units-explained",
    "betting units explained",
    "Unit size as a bankroll slice. flat-betting and bankroll-calculator stay the system and the tool.",
  ),
  p(
    22,
    "Sports betting",
    "Bet types",
    "void-bet-meaning",
    "void bet meaning",
    "Void versus push and a void parlay leg. parlay-betting-explained keeps parlay vig.",
  ),
  p(
    22,
    "Sports betting",
    "Bet types",
    "closing-line-value",
    "closing line value",
    "CLV as a price gap. implied-probability keeps the conversion.",
  ),
  p(
    22,
    "Sports betting",
    "By competition",
    "bracket-pool",
    "bracket pool",
    "Office tournament brackets. survivor-pool keeps knockout/survivor football.",
  ),
  p(
    22,
    "Games & odds",
    "RTP and tools",
    "hold-percentage-casino",
    "hold percentage casino",
    "Realized hold versus theoretical edge. house-edge keeps the definition.",
  ),
  p(
    22,
    "Slots",
    "Maths and features",
    "slot-machine-myths",
    "slot machine myths",
    "Named myths. how-to-win-at-slots and loose-slots keep RTP and payback slang.",
  ),
  p(
    22,
    "Slots",
    "Maths and features",
    "cluster-pays-slots",
    "cluster pays slots",
    "Cluster grids versus paylines. slot-paylines-explained keeps lines and ways.",
  ),
  p(
    22,
    "Slots",
    "Maths and features",
    "scatter-symbols",
    "scatter symbols",
    "Scatters and free-spin triggers. slot-paylines-explained keeps paylines.",
  ),
  p(
    22,
    "Slots",
    "Maths and features",
    "best-slot-machines-to-play",
    "best slot machines to play",
    "A comparison checklist. loose-slots keeps the loose/tight slang.",
  ),
  p(
    22,
    "Poker",
    "Variants and money",
    "rigged-poker-sites",
    "rigged poker sites",
    "Player red flags only. fake-casino-sites keeps general clone checks.",
  ),
  p(
    22,
    "Poker",
    "Variants and money",
    "collusion-in-poker",
    "collusion in poker",
    "Define collusion and reporting. No signaling method.",
  ),
  p(
    22,
    "Poker",
    "Variants and money",
    "chip-dumping",
    "chip dumping",
    "Name and impact only. No dumping method.",
  ),
  p(
    22,
    "Poker",
    "Variants and money",
    "jacks-or-better-strategy",
    "jacks or better strategy",
    "Jacks or Better holds. video-poker-paytables stays the overview; deuces-wild stays Deuces Wild.",
  ),
  p(
    22,
    "Casino games",
    "Table games",
    "mississippi-stud",
    "mississippi stud",
    "House-banked five-card stud paytable.",
  ),
  p(
    22,
    "Casino games",
    "Table games",
    "ultimate-texas-holdem",
    "ultimate texas holdem",
    "Ante, blind, and play bets. texas-holdem-rules keeps player-versus-player hold'em.",
  ),
  p(
    22,
    "Casino games",
    "Table games",
    "let-it-ride-poker",
    "let it ride poker",
    "Three-bet pull-back game.",
  ),
  p(
    22,
    "Casino games",
    "Table games",
    "crazy-4-poker",
    "crazy 4 poker",
    "Five cards, play four, queens-up.",
  ),
  p(
    22,
    "Casino games",
    "Table games",
    "baccarat-squeeze",
    "baccarat squeeze",
    "The reveal ritual. baccarat-rules keeps the bets and the edge.",
  ),
  p(
    22,
    "Slots",
    "How slots work",
    "casino-game-providers",
    "casino game providers",
    "Studios versus the operator. No fake studio ranking.",
  ),
  p(
    22,
    "Crypto payments",
    "Coins and other chains",
    "best-crypto-for-gambling",
    "best crypto for gambling",
    "Fees, speed, stability. usdc-vs-usdt-gambling keeps the stablecoin head-to-head.",
  ),
  p(
    22,
    "Crypto payments",
    "Choosing a wallet",
    "rainbow-wallet-review",
    "rainbow wallet review",
    "Self-custody review. what-is-metamask keeps MetaMask.",
  ),
  p(
    22,
    "Crypto payments",
    "Choosing a wallet",
    "metamask-vs-trust-wallet",
    "metamask vs trust wallet",
    "Comparison only. Deposit how-tos stay on the wallet casino pages.",
  ),
  p(
    22,
    "Sweepstakes",
    "Law and comparisons",
    "sweepstakes-casinos-legal-california",
    "are sweepstakes casinos legal in california",
    "California check steps. No verdict. sweepstakes-casino-legal-states keeps the moving map.",
  ),
  p(
    22,
    "Sweepstakes",
    "Law and comparisons",
    "sweepstakes-casino-taxes",
    "sweepstakes casino taxes",
    "Records and not-tax-advice. crypto-gambling-taxes keeps crypto tax.",
  ),
  p(
    22,
    "Games of chance",
    "Rummy and melds",
    "hand-and-foot-rules",
    "hand and foot rules",
    "Hand and Foot books. canasta-rules keeps canasta.",
  ),
  p(
    22,
    "Games of chance",
    "Street and hustle games",
    "beer-pong-rules",
    "beer pong rules",
    "Adult house rules for beer pong.",
  ),
  p(
    22,
    "Games of chance",
    "Street and hustle games",
    "flip-cup-rules",
    "flip cup rules",
    "Adult relay rules for flip cup.",
  ),
  p(
    22,
    "Games of chance",
    "Rummy and melds",
    "rummy-500-rules",
    "rummy 500 rules",
    "500-point rummy. how-to-play-rummy keeps basic rummy.",
  ),
  p(
    22,
    "Casino games",
    "Draw and specialty",
    "keno-vs-bingo",
    "keno vs bingo",
    "Comparison only. keno-odds and bingo-patterns keep each game.",
  ),
  p(
    22,
    "Games & odds",
    "Systems and strategy",
    "kelly-criterion-calculator",
    "kelly criterion calculator",
    "Worked numbers only. kelly-criterion keeps the theory.",
  ),
  p(
    22,
    "Games of chance",
    "Tiles and mahjong",
    "dominoes-scoring",
    "dominoes scoring",
    "Point systems only. dominoes-rules keeps how to play.",
  ),
  p(
    22,
    "CS:GO heritage",
    "Other games",
    "tf2-trading",
    "tf2 trading",
    "Trading, prices, and scams. tf2-gambling keeps betting.",
  ),
  p(
    22,
    "Foundations",
    "Web3 culture",
    "degen-gambling",
    "degen gambling",
    "Slang and bankroll. casino-terminology keeps the one-line glossary.",
  ),
  p(
    22,
    "Foundations",
    "Licenses and trust",
    "casino-account-verification",
    "casino account verification",
    "KYC documents and delays. no-kyc-casino keeps the no-KYC product.",
  ),
  // 23 — lottery, horse racing, sports bet types, prediction markets, state law, poker formats
  p(23, "Lottery", "Odds and games", "odds-of-winning-the-lottery", "odds of winning the lottery", "Combination counts. progressive-jackpot-odds keeps meters."),
  p(23, "Lottery", "Odds and games", "which-lottery-has-the-best-odds", "which lottery has the best odds", "Rank by odds and EV. Do not retarget Powerball-only odds."),
  p(23, "Lottery", "Odds and games", "powerball-odds", "powerball odds", "Prize tiers only. how-to-play-powerball keeps the rules."),
  p(23, "Lottery", "Odds and games", "how-to-play-powerball", "how to play powerball", "Rules and drawing days. powerball-odds keeps the tiers."),
  p(23, "Lottery", "Odds and games", "how-to-play-mega-millions", "how to play mega millions", "Mega Millions rules. Do not rewrite Powerball."),
  p(23, "Lottery", "After a win", "lump-sum-vs-annuity", "lump sum vs annuity", "Payout choice. lottery-taxes keeps the tax rates."),
  p(23, "Lottery", "After a win", "lottery-taxes", "lottery taxes", "Lottery withholding. report-gambling-winnings keeps Form W-2G."),
  p(23, "Lottery", "After a win", "what-to-do-if-you-win-the-lottery", "what to do if you win the lottery", "First steps. Do not rewrite the tax page."),
  p(23, "Lottery", "After a win", "claim-lottery-winnings-anonymously", "how to claim lottery winnings anonymously", "State disclosure rules. anonymous-casino stays crypto casinos."),
  p(23, "Lottery", "After a win", "lottery-pool-agreement", "lottery pool agreement", "Office pool rules. quick-pick-lottery keeps number choice."),
  p(23, "Lottery", "Odds and games", "pick-3-strategy", "pick 3 strategy", "Straight vs box maths. keno-strategy stays keno."),
  p(23, "Lottery", "Odds and games", "scratch-off-odds", "scratch off odds", "Printed overall odds. crypto-scratch-cards stays crypto."),
  p(23, "Lottery", "After a win", "lottery-calculator", "lottery calculator", "Worked after-tax jackpot. Not a W-2G form guide."),
  p(23, "Horse racing", "How to bet", "how-to-bet-on-horse-racing", "how to bet on horse racing", "Beginner tickets. handicapping-horses keeps speed figures."),
  p(23, "Horse racing", "How to bet", "win-place-show-betting", "win place show", "Straight bets only."),
  p(23, "Horse racing", "Exotic bets", "exacta-bet", "exacta bet", "Exacta box and key. Not trifecta."),
  p(23, "Horse racing", "Exotic bets", "trifecta-bet", "trifecta bet", "Trifecta box costs. Not superfecta."),
  p(23, "Horse racing", "Exotic bets", "superfecta-bet", "superfecta", "First four. Not exacta."),
  p(23, "Horse racing", "How to bet", "kentucky-derby-betting", "kentucky derby betting", "Derby field and bet types. Not a general how-to."),
  p(23, "Horse racing", "How to bet", "horse-racing-odds-explained", "horse racing odds explained", "Morning line and tote. crypto-horse-racing-betting stays virtual races."),
  p(23, "Sports betting", "Bet types", "teaser-bet", "teaser bet", "Teasers only. parlay-betting-explained keeps parlays and same-game parlays."),
  p(23, "Sports betting", "Bet types", "round-robin-bet", "round robin bet", "Round robins only."),
  p(23, "Sports betting", "Bet types", "hedge-betting", "hedge betting", "Hedge maths. Not arbitrage."),
  p(23, "Sports betting", "Bet types", "arbitrage-betting", "arbitrage betting", "Sure bets and limits. matched-betting keeps the free-bet loop."),
  p(23, "Sports betting", "Bet types", "reverse-line-movement", "reverse line movement", "RLM only. closing-line-value keeps CLV."),
  p(23, "Sports betting", "Bet types", "line-shopping", "line shopping", "Comparing prices. Not CLV theory."),
  p(23, "Sports betting", "Bet types", "vig-betting", "vig betting", "Juice maths. house-edge keeps casino edge. how-to-win-at-sports-betting keeps the process page."),
  p(23, "Sports betting", "Bet types", "push-in-betting", "push in betting", "Ties. void-bet-meaning keeps voids."),
  p(23, "Sports betting", "By competition", "puck-line", "puck line", "NHL 1.5 only."),
  p(23, "Sports betting", "By competition", "run-line", "run line", "MLB 1.5 only."),
  p(23, "Sports betting", "By competition", "draw-no-bet", "draw no bet", "Soccer DNB. soccer-betting keeps the sport overview."),
  p(23, "Sports betting", "By competition", "asian-handicap", "asian handicap", "Quarter lines. Not DNB."),
  p(23, "Sports betting", "By competition", "both-teams-to-score", "both teams to score", "BTTS only."),
  p(23, "Sports betting", "Bet types", "futures-bet", "futures bet", "Season-long prices. Not a hedge guide."),
  p(23, "Sports betting", "Bet types", "alternate-lines", "alternate lines", "Alt spreads and totals. point-spread-explained keeps the standard spread."),
  p(23, "Sports betting", "Bet types", "bet-tracker", "bet tracker", "A log. bankroll-calculator keeps sizing."),
  p(23, "Sports betting", "Bet types", "bonus-bets-explained", "bonus bet", "Sportsbook free bets. casino-bonuses-explained and matched-betting stay separate."),
  p(23, "Sports betting", "Office pools", "super-bowl-squares", "super bowl squares", "Squares only. bracket-pool keeps brackets."),
  p(23, "Sports betting", "By competition", "march-madness-betting", "march madness betting", "Sportsbook market. bracket-pool keeps the office bracket."),
  p(23, "Sports betting", "By competition", "wnba-betting", "wnba betting", "WNBA only. nba-betting keeps the NBA."),
  p(23, "Prediction markets", "Pick'em and fantasy", "how-does-prizepicks-work", "prizepicks", "PrizePicks payouts. Do not target the bare phrase pick em."),
  p(23, "Prediction markets", "Pick'em and fantasy", "underdog-fantasy-review", "underdog fantasy", "Underdog product. Not PrizePicks."),
  p(23, "Prediction markets", "Pick'em and fantasy", "dfs-strategy", "dfs strategy", "Cash vs GPP. Not a PrizePicks review."),
  p(23, "Prediction markets", "Event contracts", "kalshi-review", "kalshi review", "Fees and markets. polymarket-vs-kalshi keeps the comparison."),
  p(23, "Prediction markets", "Event contracts", "is-kalshi-gambling", "is kalshi gambling", "Named-venue legal frame. prediction-market-legal-us stays general."),
  p(23, "Prediction markets", "Event contracts", "how-does-polymarket-work", "how does polymarket work", "How shares settle. Not the Kalshi comparison."),
  p(23, "Prediction markets", "Event contracts", "election-betting-odds", "election betting odds", "Reading political prices. Not a Kalshi review."),
  p(23, "Prediction markets", "Event contracts", "is-day-trading-gambling", "is day trading gambling", "Trading vs casino EV. Do not target is crypto gambling."),
  p(23, "Foundations", "US casino law", "is-gambling-legal-in-texas", "is gambling legal in texas", "Texas only. Not a Hold'em page."),
  p(23, "Foundations", "US casino law", "is-gambling-legal-in-california", "is gambling legal in california", "Statewide map. sweepstakes-casinos-legal-california keeps sweeps."),
  p(23, "Foundations", "US casino law", "is-gambling-legal-in-georgia", "is gambling legal in georgia", "Georgia only."),
  p(23, "Foundations", "US casino law", "is-gambling-legal-in-tennessee", "is gambling legal in tennessee", "Tennessee only."),
  p(23, "Foundations", "US casino law", "online-gambling-legal-north-carolina", "is online gambling legal in north carolina", "North Carolina only."),
  p(23, "Foundations", "US casino law", "online-casino-legal-new-york", "is online gambling legal in new york", "New York only. is-online-casino-legal stays national."),
  p(23, "Poker", "Learn the game", "poker-positions", "poker positions", "Seat map. texas-holdem-strategy keeps ranges and bet size."),
  p(23, "Poker", "Learn the game", "omaha-poker-rules", "omaha poker rules", "PLO rules. texas-holdem-rules stays Hold'em."),
  p(23, "Poker", "Learn the game", "seven-card-stud", "seven card stud", "Stud streets. Not Hold'em."),
  p(23, "Poker", "Strategy", "poker-tells", "poker tells", "Tells only. Not a bluff manual."),
  p(23, "Poker", "Strategy", "bluffing-in-poker", "bluffing in poker", "Bluff frequency. poker-tells stays tells."),
  p(23, "Games & odds", "PvP maths", "how-to-play-roulette", "how to play roulette", "Beginner rules. how-to-win-at-roulette keeps strategy. Do not compare American vs European odds as the page job."),
  p(23, "Games & odds", "PvP maths", "roulette-table-layout", "roulette table layout", "Felt and wheel order. roulette-colors keeps colour odds."),
  p(23, "Games & odds", "PvP maths", "roulette-simulator", "roulette simulator", "Educational spins. Not the live wheel and not a strategy system."),
  p(23, "Games & odds", "Tables, tickets and bets", "bingo-odds", "bingo odds", "Cover probability. bingo-patterns keeps shapes. crypto-bingo keeps the crypto product."),
  p(23, "Responsible play", "Addiction and help", "gambling-debt", "gambling debt", "Debt steps. sunk-cost-fallacy-gambling keeps chasing losses."),
  p(23, "Casino knowledge", "Culture and belief", "sports-betting-scandals", "sports betting scandal", "Historical cases. esports-match-fixing stays esports."),
  p(23, "Casino knowledge", "Culture and belief", "famous-casino-heists", "casino heist", "Robberies. casino-surveillance stays the camera system."),
  p(23, "Casino knowledge", "Culture and belief", "gambling-superstitions", "gambling superstitions", "Roundup. lucky-numbers-gambling and horseshoe-luck stay the specific beliefs."),
  p(23, "Foundations", "Taxes", "gambling-tax-calculator", "gambling tax calculator", "Estimate only. report-gambling-winnings keeps Form W-2G."),
];
