/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CoinflipRouteImport } from './routes/coinflip'
import { Route as FairnessRouteImport } from './routes/fairness'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResponsibleGamblingRouteImport } from './routes/responsible-gambling'
import { Route as RouletteRouteImport } from './routes/roulette'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as CoinflipGameIdRouteImport } from './routes/coinflip.$gameId'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'
import { Route as ApiPublicAvatarStyleSeedRouteImport } from './routes/api/public/avatar.$style.$seed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinflipRoute = CoinflipRouteImport.update({
  id: '/coinflip',
  path: '/coinflip',
  getParentRoute: () => rootRouteImport,
} as any)
const FairnessRoute = FairnessRouteImport.update({
  id: '/fairness',
  path: '/fairness',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleGamblingRoute = ResponsibleGamblingRouteImport.update({
  id: '/responsible-gambling',
  path: '/responsible-gambling',
  getParentRoute: () => rootRouteImport,
} as any)
const RouletteRoute = RouletteRouteImport.update({
  id: '/roulette',
  path: '/roulette',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CoinflipGameIdRoute = CoinflipGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => CoinflipRoute,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvatarStyleSeedRoute =
  ApiPublicAvatarStyleSeedRouteImport.update({
    id: '/api/public/avatar/$style/$seed',
    path: '/api/public/avatar/$style/$seed',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coinflip': typeof CoinflipRouteWithChildren
  '/fairness': typeof FairnessRoute
  '/privacy': typeof PrivacyRoute
  '/responsible-gambling': typeof ResponsibleGamblingRoute
  '/roulette': typeof RouletteRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/coinflip/$gameId': typeof CoinflipGameIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/api/public/avatar/$style/$seed': typeof ApiPublicAvatarStyleSeedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coinflip': typeof CoinflipRouteWithChildren
  '/fairness': typeof FairnessRoute
  '/privacy': typeof PrivacyRoute
  '/responsible-gambling': typeof ResponsibleGamblingRoute
  '/roulette': typeof RouletteRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/coinflip/$gameId': typeof CoinflipGameIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/api/public/avatar/$style/$seed': typeof ApiPublicAvatarStyleSeedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/coinflip': typeof CoinflipRouteWithChildren
  '/fairness': typeof FairnessRoute
  '/privacy': typeof PrivacyRoute
  '/responsible-gambling': typeof ResponsibleGamblingRoute
  '/roulette': typeof RouletteRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/coinflip/$gameId': typeof CoinflipGameIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/api/public/avatar/$style/$seed': typeof ApiPublicAvatarStyleSeedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/coinflip'
    | '/fairness'
    | '/privacy'
    | '/responsible-gambling'
    | '/roulette'
    | '/terms'
    | '/admin'
    | '/profile'
    | '/wallet'
    | '/coinflip/$gameId'
    | '/games/$gameId'
    | '/api/public/avatar/$style/$seed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/coinflip'
    | '/fairness'
    | '/privacy'
    | '/responsible-gambling'
    | '/roulette'
    | '/terms'
    | '/admin'
    | '/profile'
    | '/wallet'
    | '/coinflip/$gameId'
    | '/games/$gameId'
    | '/api/public/avatar/$style/$seed'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/coinflip'
    | '/fairness'
    | '/privacy'
    | '/responsible-gambling'
    | '/roulette'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/profile'
    | '/_authenticated/wallet'
    | '/coinflip/$gameId'
    | '/games/$gameId'
    | '/api/public/avatar/$style/$seed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CoinflipRoute: typeof CoinflipRouteWithChildren
  FairnessRoute: typeof FairnessRoute
  PrivacyRoute: typeof PrivacyRoute
  ResponsibleGamblingRoute: typeof ResponsibleGamblingRoute
  RouletteRoute: typeof RouletteRoute
  TermsRoute: typeof TermsRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  ApiPublicAvatarStyleSeedRoute: typeof ApiPublicAvatarStyleSeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coinflip': {
      id: '/coinflip'
      path: '/coinflip'
      fullPath: '/coinflip'
      preLoaderRoute: typeof CoinflipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fairness': {
      id: '/fairness'
      path: '/fairness'
      fullPath: '/fairness'
      preLoaderRoute: typeof FairnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-gambling': {
      id: '/responsible-gambling'
      path: '/responsible-gambling'
      fullPath: '/responsible-gambling'
      preLoaderRoute: typeof ResponsibleGamblingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roulette': {
      id: '/roulette'
      path: '/roulette'
      fullPath: '/roulette'
      preLoaderRoute: typeof RouletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/coinflip/$gameId': {
      id: '/coinflip/$gameId'
      path: '/$gameId'
      fullPath: '/coinflip/$gameId'
      preLoaderRoute: typeof CoinflipGameIdRouteImport
      parentRoute: typeof CoinflipRoute
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/avatar/$style/$seed': {
      id: '/api/public/avatar/$style/$seed'
      path: '/api/public/avatar/$style/$seed'
      fullPath: '/api/public/avatar/$style/$seed'
      preLoaderRoute: typeof ApiPublicAvatarStyleSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CoinflipRouteChildren {
  CoinflipGameIdRoute: typeof CoinflipGameIdRoute
}

const CoinflipRouteChildren: CoinflipRouteChildren = {
  CoinflipGameIdRoute: CoinflipGameIdRoute,
}

const CoinflipRouteWithChildren = CoinflipRoute._addFileChildren(
  CoinflipRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CoinflipRoute: CoinflipRouteWithChildren,
  FairnessRoute: FairnessRoute,
  PrivacyRoute: PrivacyRoute,
  ResponsibleGamblingRoute: ResponsibleGamblingRoute,
  RouletteRoute: RouletteRoute,
  TermsRoute: TermsRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  ApiPublicAvatarStyleSeedRoute: ApiPublicAvatarStyleSeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
