import type { Guide } from "./types";

export const guide: Guide = {
  slug: "sent-crypto-to-wrong-network",
  cluster: "Crypto payments",
  keyword: "sent crypto to wrong network",
  secondary: ["wrong chain crypto transfer", "crypto sent on wrong network"],
  title: "Sent Crypto to the Wrong Network: What Happens",
  h1: "Sent Crypto to the Wrong Network: What Happens",
  description:
    "Sent crypto to the wrong network often stays where the receiving wallet has no key. Learn how that differs from a stuck transfer, without a recovery promise.",
  answer:
    "Sent crypto to wrong network means the chain you selected included the transfer, and the receiver was watching a different chain. The transaction can show a success mark. The explorer on the network you picked can show the tokens at the destination address. The explorer on the network you were supposed to use can show nothing. Both facts can be true. You did not create a pending payment on the right chain. You created a finished payment on the wrong one.\n\nThis page is only that case. If the hash is still pending, dropped, or blocked by an earlier nonce on the correct network, stop here and use [stuck crypto transaction](/guides/stuck-crypto-transaction). Fee bumps and replacements do not apply to a transfer that already succeeded somewhere else. [Crypto bridge](/guides/crypto-bridge) explains a planned move of coins you control from one chain to another. It is not a recovery manual for funds sitting with someone who cannot sign, and this article will not turn it into one.",
  facts: [],
  sections: [
    {
      id: "what-wrong-network-looks-like",
      title: 'What "wrong network" looks like',
      body: 'You held an asset that exists on more than one chain, or you held a native coin whose name is reused in branding across chains. The receiver told you the chain. The withdrawal screen or the wallet offered a list. You chose a different row. The address you pasted was valid enough that the wallet did not stop you, or you overrode a warning. The network accepted the signature. Miners, validators, or the sequencer included it. From that network\'s point of view, nothing failed.\n\nThe receiver\'s watcher never fires, because it is subscribed to another ledger. Support says they do not see the deposit. You search the hash on the wrong explorer and also see nothing, which deepens the confusion. The hash has to be opened on the network your wallet actually used when it broadcast. That single check separates "the chain has my transfer" from "I am searching a chain that never saw it."\n\nWrong asset on the right network is a cousin mistake, not this one. Wrong memo on the right network is a cousin mistake, not this one. This page stays on the chain mismatch. If the explorer on the intended network shows your hash as successful to the right address, you are not in the wrong-network case. Look at token display, memos, and cashier delays instead.\n\nGambling is for adults 21 and older, and only with money you can afford to lose. A wrong-network deposit is not a bet you can win back by playing. It is a transfer error. Fix the diagnosis before you send anything else.',
    },
    {
      id: "why-recovery-is-often-impossible",
      title: "Why recovery is often impossible",
      body: 'An address is a destination on the chain that recorded it. Controlling the coins requires a private key that can sign on that chain, plus software that can build the transaction. If the receiver is an exchange or a casino that does not operate a wallet on that chain, they may not have the key online, or they may not have the key at all. They cannot broadcast a refund from a system they do not run. You cannot broadcast it for them. A bridge contract cannot reach into their address and pull the tokens out, because a bridge moves value the bridge\'s rules allow from an account that signed or from a pool, not from a stranger\'s account that never opted in.\n\nThat is why a promise of guaranteed recovery is not honest. Some receivers help when they do hold keys on the unexpected chain, as a courtesy or as a paid support process they publish. Some do not, even if they technically could. Some cannot. Until they say which, in writing, on their official site, the coins are not "almost back." They are on the chain you chose, at the address you chose.\n\nYour own wallet is the exception that still is not a promise. On many Ethereum-style chains, the same key produces the same address text. If you sent to your own address on a chain you did not mean, the tokens may sit at that address on the chain that received them. Opening that chain in a wallet that holds your key can reveal them. You are not bridging someone else\'s money. You are looking at your own account with the correct network selected. If the token is a contract the wallet does not list by default, the wallet may hide a balance that the explorer shows. The explorer is the check. If the explorer shows the tokens at your address, you have a chance, and you still have to move them with your own signature, carefully, without following a random helper. If the explorer shows them at an address you do not control, the chance belongs to whoever holds that key, not to a tutorial.\n\nHardware wallets and passphrases complicate the "it is my address" hope. A different passphrase yields a different account. An address you do not recognize is not saved by optimism. Match the address on the explorer to an address your wallet can display on that chain. No match means you do not have the key in the wallet you are holding.',
    },
    {
      id: "what-to-do-in-the-first-hour",
      title: "What to do in the first hour",
      body: "Stop sending. A second transfer on the correct network is a second payment, not a repair. Make it only if you still mean to pay and you have written off the first amount or been told in a credible way that the first amount will not be credited.\n\nFind the hash in the sending wallet's history. Note the network the wallet shows for that history entry. Open an explorer for that network only. Confirm the status is success, note the destination, and note the token contract if one is listed. Screenshot the explorer, not your seed phrase.\n\nIf the destination was your own wallet, use the explorer result and your own wallet's network switch. Do not type the recovery phrase into a website that offers to scan for lost funds. A real wallet can add a network and show an address without a webpage that asks for the words. If you are unsure how your wallet adds a network, use the wallet vendor's own help, and stop if the next step requests the phrase.\n\nIf the destination was another person, tell them the network and the hash. They may control the same address text on that chain. They may not. They are allowed to refuse. You are not allowed to demand they install software and sign something they do not understand for your mistake.\n\nIf the destination was an exchange or a casino cashier, open a ticket on that company's official site. Give the hash, the amount, the asset ticker, the network you used, and the network you were supposed to use. Ask whether they custody that network for that address. Accept a no. A no is a complete answer. Do not escalate by depositing more so they will \"unlock\" the first transfer. Do not move the conversation to a direct message with a new agent who appeared overnight.\n\nPVPspinArena offers jackpot, coinflip, and roulette settled in USD. Deposit and payout wallets are separate. A deposit address is only meaningful on the asset and network the cashier listed when you copied it. This page does not describe the site's treasury and does not promise that a mismatched chain can be credited. If you have a hash, the explorer for the network you actually used is the record. The cashier on a different network will not invent a matching deposit from that record.",
    },
    {
      id: "scams-that-attach-themselves-to-this-mistake",
      title: "Scams that attach themselves to this mistake",
      body: 'Search results and social replies know the phrase "sent crypto to the wrong network." They sell a recovery service. The pitch is confident, the logo looks technical, and the next step is your seed phrase, a remote-control app, or an upfront fee in a second coin. The seed phrase hands them every chain you control, including the funds you did not lose. The fee buys a story. A remote app lets them sign as you.\n\nNo legitimate explorer, wallet vendor, or casino needs the recovery phrase to look at a public hash. The hash is already public. You can paste it into an explorer yourself. Anyone who cannot start from the hash, and instead starts from the phrase, is taking the remaining coins.\n\nA bridge website that asks you to connect the wallet that does not hold the lost funds, and to approve a token spend, is not restoring the mistaken transfer. Approvals can empty the wallet you still have. [Crypto bridge](/guides/crypto-bridge) is for a deliberate move you initiate because you hold the asset on the source chain and you want it on the destination chain. Read it before you plan a real bridge. Do not read it as permission to chase this loss through a contract a stranger picked.\n\nSupport impersonation is the other costume. You post the hash in public. Someone replies as the exchange. They ask you to "verify" on a site they control. The real ticket stays inside the account you opened by typing the exchange\'s address yourself. If you already posted the hash, the damage of the post is privacy, not the phrase, unless you also posted the phrase. Do not add the phrase to fix the privacy.',
    },
    {
      id: "how-this-differs-from-a-slow-confirmation",
      title: "How this differs from a slow confirmation",
      body: "A slow confirmation still refers to one network. The count climbs, or it does not, on the chain you selected. The receiver who watches that chain will eventually see the same hash. Wrong network means the success, if it exists, is visible only on the chain that got the broadcast. Waiting overnight will not copy the transfer onto the other chain. Bridges and exchanges copy value between chains only when someone who controls the source signs a new operation, or when their own systems agree to credit you. Waiting is not that signature.\n\nIf you are unsure which case you are in, answer three questions. Which network did the sending wallet use? Does an explorer for that network show success? Does an explorer for the intended network show the same hash? Success on the first and absence on the second is the wrong-network case. Absence on both may mean you never broadcast, or you are still on the wrong explorer. Success on the intended network means you do not have this problem, even if a cashier is slow.\n\nWrite those answers down before you pay anyone to interpret them. The answers are free. The hash is enough to produce them.",
    },
    {
      id: "preventing-the-next-one",
      title: "Preventing the next one",
      body: 'Read the network name at the moment of sending, from the receiver\'s page, out loud. Match it to the network dropdown. Match the fee asset to that network. Match the address shape if the chains use different shapes. Send a small test to a new destination and wait until it is visible on the intended explorer before you send the rest. Save the hash next to the network name so the next search starts in the right place.\n\nWhen you publish your own receive address, publish the network in the same line. "USDT" is not an instruction. The chain is the instruction. People recreate this loss because the invoice was incomplete. Your invoice can be complete.\n\nIf you must move value between chains on purpose, decide that before you send, use a method you can explain, and keep the destination as an address you control until the value is on the right chain. The bridge guide is the background for that planned move. A casino deposit is the last hop, on the chain the cashier named, not the hop where you experiment.\n\nThere is no hidden reversal in the confirmation checkmark. The checkmark means the network you used accepted the payment. Choose the network as carefully as the amount. After the checkmark, tell the truth about which chain you used, protect the keys you still have, and treat recovery as uncertain unless the key holder on that chain can sign and agrees to.\n\nThe rest of this subject is on the [Crypto payments guides](/guides/topics/crypto-payments). See [stuck crypto transaction](/guides/stuck-crypto-transaction), [crypto bridge](/guides/crypto-bridge), [crypto wallet for gambling](/guides/crypto-wallet-for-gambling). PVPspinArena settles jackpot, coinflip, and roulette in US dollars. Read [wallet](/wallet) before you play.',
    },
  ],
  faqs: [
    {
      q: "Is a wrong-network send the same as a pending send?",
      a: "No, a pending send is still waiting on the chain you selected, and the stuck crypto transaction page covers nonce and fee problems there. A wrong-network send often confirms on a different chain, which means it is finished in the place you did not intend.",
    },
    {
      q: "Can the coins be recovered?",
      a: "Sometimes, and often they cannot, so this page does not promise a recovery. If the receiving wallet does not control that chain, you cannot force the coins back, and a bridge cannot move funds from an address you or they cannot sign for.",
    },
    {
      q: "What if the address was my own wallet?",
      a: "If you hold the keys and that same address exists on the chain that actually received the tokens, you may be able to see them by opening that chain in your own wallet. That is your key on that chain, not a promise, and it is not a tool for moving someone else's funds.",
    },
    {
      q: "What if I sent it to an exchange or a casino?",
      a: "Contact them with the hash and the network you actually used, and accept that they may have no wallet on that chain. Do not send a second payment, and do not pay a stranger who claims they can reverse the first one.",
    },
    {
      q: "Should I use a bridge to fix it?",
      a: "A bridge is for a planned move of assets you already control, which is what the crypto bridge guide explains. It is not a rescue button for coins sitting at an address nobody can sign, and this page will not give a bridge tutorial for that case.",
    },
  ],
  sources: [],
  related: ["stuck-crypto-transaction", "crypto-bridge"],
  updated: "2026-09-26",
};
